### ISSUE TITLE
dependencia onelogin/php-saml 

### ISSUE THREAD

**Issue by Adolf0100** [rediris-es/samlPoA#1]
El modulo mcrypt esta deprecado en version de php 7.3. Parece que php-saml 3.0.0 no depende de mcrypt. 

php-saml 2.11 requiere mcrypt que con las versiones de php mencionadas es imposible por lo que es imposible utilizarlo....

**Comment by lonoak** [comment]
Actualizada la dependencia de `one-login/php-saml` a `^3.3` en la rama `devel`. Instala bien, pero necesita probarse.

**Comment by lonoak** [comment]
Solucionado en #2
